name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request_target:

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm i

      - name: Linting
        run: npx -y prettier -c .

      - name: Type check
        run: npx -y tsc --strict
